// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TiendaOnline.Infrastructure.Data;

#nullable disable

namespace TiendaOnline.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250511095708_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TiendaOnline.Domain.Models.Color", b =>
                {
                    b.Property<int>("ColorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ColorId"));

                    b.Property<string>("ColorNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ColorId");

                    b.ToTable("Colores");

                    b.HasData(
                        new
                        {
                            ColorId = 1,
                            ColorNombre = "Amarillo"
                        },
                        new
                        {
                            ColorId = 2,
                            ColorNombre = "Azul"
                        },
                        new
                        {
                            ColorId = 3,
                            ColorNombre = "Azul Marino"
                        },
                        new
                        {
                            ColorId = 4,
                            ColorNombre = "Beige"
                        },
                        new
                        {
                            ColorId = 5,
                            ColorNombre = "Blanco"
                        },
                        new
                        {
                            ColorId = 6,
                            ColorNombre = "Caqui"
                        },
                        new
                        {
                            ColorId = 7,
                            ColorNombre = "Celeste"
                        },
                        new
                        {
                            ColorId = 8,
                            ColorNombre = "Coral"
                        },
                        new
                        {
                            ColorId = 9,
                            ColorNombre = "Dorado"
                        },
                        new
                        {
                            ColorId = 10,
                            ColorNombre = "Fucsia"
                        },
                        new
                        {
                            ColorId = 11,
                            ColorNombre = "Gris"
                        },
                        new
                        {
                            ColorId = 12,
                            ColorNombre = "Marrón"
                        },
                        new
                        {
                            ColorId = 13,
                            ColorNombre = "Morado"
                        },
                        new
                        {
                            ColorId = 14,
                            ColorNombre = "Naranja"
                        },
                        new
                        {
                            ColorId = 15,
                            ColorNombre = "Negro"
                        },
                        new
                        {
                            ColorId = 16,
                            ColorNombre = "Plateado"
                        },
                        new
                        {
                            ColorId = 17,
                            ColorNombre = "Rosa"
                        },
                        new
                        {
                            ColorId = 18,
                            ColorNombre = "Rojo"
                        },
                        new
                        {
                            ColorId = 19,
                            ColorNombre = "Turquesa"
                        },
                        new
                        {
                            ColorId = 20,
                            ColorNombre = "Verde"
                        });
                });

            modelBuilder.Entity("TiendaOnline.Domain.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TallaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("TallaId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("TiendaOnline.Domain.Models.Talla", b =>
                {
                    b.Property<int>("TallaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TallaId"));

                    b.Property<string>("TallaNombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TallaId");

                    b.ToTable("Tallas");

                    b.HasData(
                        new
                        {
                            TallaId = 1,
                            TallaNombre = "0-3 meses"
                        },
                        new
                        {
                            TallaId = 2,
                            TallaNombre = "3-6 meses"
                        },
                        new
                        {
                            TallaId = 3,
                            TallaNombre = "6-9 meses"
                        },
                        new
                        {
                            TallaId = 4,
                            TallaNombre = "9-12 meses"
                        },
                        new
                        {
                            TallaId = 5,
                            TallaNombre = "12-18 meses"
                        },
                        new
                        {
                            TallaId = 6,
                            TallaNombre = "2 años"
                        },
                        new
                        {
                            TallaId = 7,
                            TallaNombre = "3 años"
                        },
                        new
                        {
                            TallaId = 8,
                            TallaNombre = "4 años"
                        },
                        new
                        {
                            TallaId = 9,
                            TallaNombre = "5 años"
                        },
                        new
                        {
                            TallaId = 10,
                            TallaNombre = "6 años"
                        },
                        new
                        {
                            TallaId = 11,
                            TallaNombre = "8 años"
                        },
                        new
                        {
                            TallaId = 12,
                            TallaNombre = "10 años"
                        },
                        new
                        {
                            TallaId = 13,
                            TallaNombre = "12 años"
                        },
                        new
                        {
                            TallaId = 14,
                            TallaNombre = "14 años"
                        },
                        new
                        {
                            TallaId = 15,
                            TallaNombre = "S"
                        },
                        new
                        {
                            TallaId = 16,
                            TallaNombre = "M"
                        },
                        new
                        {
                            TallaId = 17,
                            TallaNombre = "L"
                        },
                        new
                        {
                            TallaId = 18,
                            TallaNombre = "XL"
                        },
                        new
                        {
                            TallaId = 19,
                            TallaNombre = "XXL"
                        },
                        new
                        {
                            TallaId = 20,
                            TallaNombre = "3XL"
                        });
                });

            modelBuilder.Entity("TiendaOnline.Domain.Models.Producto", b =>
                {
                    b.HasOne("TiendaOnline.Domain.Models.Color", "Color")
                        .WithMany("Productos")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TiendaOnline.Domain.Models.Talla", "Talla")
                        .WithMany("Productos")
                        .HasForeignKey("TallaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("Talla");
                });

            modelBuilder.Entity("TiendaOnline.Domain.Models.Color", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("TiendaOnline.Domain.Models.Talla", b =>
                {
                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
